INSERT INTO USUARIO(NOME, SEXO, EMAIL, CPF, DATA_DE_NASCIMENTO, NATURALIDADE, NACIONALIDADE) VALUES ('Bia', 'F', 'bia@home.com', '01234567890', '1988-02-20', 'Rio de Janeiro', 'Brasileira');
INSERT INTO USUARIO(NOME, SEXO, EMAIL, CPF, DATA_DE_NASCIMENTO, NATURALIDADE, NACIONALIDADE) VALUES ('Carlos', 'M', 'carolos@home.com.be', '01234567880', '1981-04-11', 'Rio de Janeiro', 'Brasileira');
INSERT INTO USUARIO(NOME, SEXO, EMAIL, CPF, DATA_DE_NASCIMENTO, NATURALIDADE, NACIONALIDADE) VALUES ('Ricardo', 'M', NULL, '01234567870', '1995-07-03', 'São Paulo', 'Brasileira');
