INSERT INTO USUARIO(NOME, SEXO, EMAIL, CPF, DATA_DE_NASCIMENTO, NATURALIDADE, NACIONALIDADE)
VALUES ('Bia', 'F', 'bia@home.com', '1988-02-20', 'Rio de Janeiro', 'Brasileira');
INSERT INTO USUARIO(NOME, SEXO, EMAIL, CPF, DATA_DE_NASCIMENTO, NATURALIDADE, NACIONALIDADE)
VALUES ('Carlos', 'M', 'carolos@home.com.be', '1981-04-11', 'Rio de Janeiro', 'Brasileira');
INSERT INTO USUARIO(NOME, SEXO, EMAIL, CPF, DATA_DE_NASCIMENTO, NATURALIDADE, NACIONALIDADE)
VALUES ('Ricardo', 'M', NULL, '1995-07-03', 'São Paulo', 'Brasileira');
